namespace AudioSensei.Bass
{
    internal enum BassConfig : uint
    {
        Buffer = 0,
        UpdatePeriod = 1,
        GlobalVolumeSample = 4,
        GlobalVolumeStream = 5,
        GlobalVolumeMusic = 6,
        CurveVol = 7,
        CurvePan = 8,
        FloatDsp = 9,
        Algorithm3D = 10,
        NetTimeout = 11,
        NetBuffer = 12,
        PauseNoplay = 13,
        NetPrebuf = 15,
        NetPassive = 18,
        RecBuffer = 19,
        NetPlaylist = 21,
        MusicVirtual = 22,
        Verify = 23,
        UpdateThreads = 24,
        DevBuffer = 27,
        RecLoopback = 28,
        VistaTruepos = 30,
        IosSession = 34,
        IosMixAudio = 34,
        DevDefault = 36,
        NetReadtimeout = 37,
        VistaSpeakers = 38,
        IosSpeaker = 39,
        MfDisable = 40,
        Handles = 41,
        Unicode = 42,
        Src = 43,
        SrcSample = 44,
        AsyncFileBuffer = 45,
        OggPrescan = 47,
        MfVideo = 48,
        Airplay = 49,
        DevNonStop = 50,
        IosNoCategory = 51,
        VerifyNet = 52,
        DevPeriod = 53,
        Float = 54,
        NetSeek = 56,
        AmDisable = 58,
        NetPlaylistDepth = 59,
        NetPrebufWait = 60,
        AndroidSessionid = 62,
        WasapiPersist = 65,
        RecWasapi = 66,
        AndroidAAudio = 67,
        // BASS_SetConfigPtr options
        NetAgent = 16,
        NetProxy = 17,
        IosNotify = 46,
        Libssl = 64
    }
}
