name: .NET Core CI

on: [push, pull_request]

jobs:
  build:

    name: .Net Core ${{ matrix.framework }} on ${{ matrix.os }} for ${{ matrix.target }}-${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        framework: ['3.1']
        arch: ['x86', 'x64']
        exclude: 
        - os: ubuntu-latest
          arch: 'x86'
        - os: macos-latest
          arch: 'x86'
        include: 
        - os: windows-latest
          target: win
        - os: ubuntu-latest
          target: linux
        - os: macos-latest
          target: osx
    timeout-minutes: 30

    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true

    steps:
    - uses: actions/checkout@v2.3.3
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: ${{ matrix.framework }}
      
    - name: Install dependencies
      run: dotnet restore -r ${{ matrix.target }}-${{ matrix.arch }}
      
    - name: Build ${{ matrix.target }}-${{ matrix.arch }}
      run: dotnet publish -r ${{ matrix.target }}-${{ matrix.arch }} -c release
      
    - name: Test
      run: dotnet test --runtime ${{ matrix.target }}-${{ matrix.arch }}
      
    - name: Upload ${{ matrix.target }}-${{ matrix.arch }}
      uses: actions/upload-artifact@v2
      with:
        name: AudioSensei-${{ matrix.target }}-${{ matrix.arch }}
        path: ${{ github.workspace }}/AudioSensei/bin/Release/netcoreapp${{ matrix.framework }}/${{ matrix.target }}-${{ matrix.arch }}/publish
