name: .NET Core CI

on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.framework }} from .Net ${{ matrix.frameworkversion }} on ${{ matrix.os }} for ${{ matrix.target }}-${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        frameworkversion: ['5.0']
        arch: ['x64']
        include: 
        - os: windows-latest
          target: win
          framework: net5.0-windows
    timeout-minutes: 30

    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true

    steps:
    - uses: actions/checkout@v4.1.0
      
    - name: Setup .Net
      uses: actions/setup-dotnet@v3.2.0
      with:
        dotnet-version: ${{ matrix.frameworkversion }}
      
    - name: Install dependencies
      run: dotnet restore -r ${{ matrix.target }}-${{ matrix.arch }}
      
    - name: Build ${{ matrix.target }}-${{ matrix.arch }}
      run: dotnet publish -r ${{ matrix.target }}-${{ matrix.arch }} -c release -f ${{ matrix.framework }}
      
    - name: Test
      run: dotnet test --runtime ${{ matrix.target }}-${{ matrix.arch }} -f ${{ matrix.framework }}
      
    - name: Upload ${{ matrix.target }}-${{ matrix.arch }}
      uses: actions/upload-artifact@v3
      with:
        name: AudioSensei-${{ matrix.target }}-${{ matrix.arch }}
        path: ${{ github.workspace }}/AudioSensei/bin/Release/${{ matrix.framework }}/${{ matrix.target }}-${{ matrix.arch }}/publish
