name: .NET Core CI

on: [push, pull_request]

jobs:
  build:

    name: ${{ matrix.framework }} from .Net ${{ matrix.frameworkversion }} on ${{ matrix.os }} for ${{ matrix.target }}-${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        frameworkversion: ['5.0']
        arch: ['x86', 'x64']
        exclude: 
        - os: ubuntu-latest
          arch: 'x86'
        - os: macos-latest
          arch: 'x86'
        include: 
        - os: windows-latest
          target: win
          framework: net5.0-windows
        - os: ubuntu-latest
          target: linux
          framework: net5.0
        - os: macos-latest
          target: osx
          framework: net5.0
    timeout-minutes: 30

    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true

    steps:
    - uses: actions/checkout@v2.4.0
      
    - name: Setup .Net
      uses: actions/setup-dotnet@v1.9.0
      with:
        dotnet-version: ${{ matrix.frameworkversion }}
      
    - name: Install dependencies
      run: dotnet restore -r ${{ matrix.target }}-${{ matrix.arch }}
      
    - name: Build ${{ matrix.target }}-${{ matrix.arch }}
      run: dotnet publish -r ${{ matrix.target }}-${{ matrix.arch }} -c release -f ${{ matrix.framework }}
      
    - name: Test
      run: dotnet test --runtime ${{ matrix.target }}-${{ matrix.arch }} -f ${{ matrix.framework }}
      
    - name: Upload ${{ matrix.target }}-${{ matrix.arch }}
      uses: actions/upload-artifact@v3
      with:
        name: AudioSensei-${{ matrix.target }}-${{ matrix.arch }}
        path: ${{ github.workspace }}/AudioSensei/bin/Release/${{ matrix.framework }}/${{ matrix.target }}-${{ matrix.arch }}/publish
