name: .NET Core CI

on: [push, pull_request]

jobs:
  build:

    name: .Net Core ${{ matrix.framework }} on ${{ matrix.os }} for ${{ matrix.target }}-${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        framework: ['3.1']
        arch: ['x86', 'x64', 'arm', 'arm64']
        exclude: 
        - os: ubuntu-latest
          arch: 'x86'
        - os: windows-latest
          arch: 'arm'
        - os: windows-latest
          arch: 'arm64'
        include: 
        - os: windows-latest
          target: win
        - os: ubuntu-latest
          target: linux
    timeout-minutes: 30

    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true

    steps:
    - uses: actions/checkout@v2.3.3
    
    - if: matrix.arch == 'arm' || matrix.arch == 'arm64'
      name: Setup QEMU
      run: docker run --rm --privileged multiarch/qemu-user-static:register

    - if: matrix.arch == 'arm' || matrix.arch == 'arm64'
      name: Enter container
      run: docker run --rm multiarch/debian-debootstrap:arm64-stretch
      
    - name: Teststst
      run: uname -m

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: ${{ matrix.framework }}
      
    - name: Install dependencies
      run: dotnet restore -r ${{ matrix.target }}-${{ matrix.arch }}
      
    - name: Build ${{ matrix.target }}-${{ matrix.arch }}
      run: dotnet publish -r ${{ matrix.target }}-${{ matrix.arch }} -c release
      
    - name: Test
      run: dotnet test --runtime ${{ matrix.target }}-${{ matrix.arch }}
      
    - name: Upload ${{ matrix.target }}-${{ matrix.arch }}
      uses: actions/upload-artifact@v2
      with:
        name: AudioSensei-${{ matrix.target }}-${{ matrix.arch }}
        path: ${{ github.workspace }}/AudioSensei/bin/Release/netcoreapp${{ matrix.framework }}/${{ matrix.target }}-${{ matrix.arch }}/publish
